# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56b75113f9fcdc3f2fd295709f82a298aa9c79ac76216a77dcd889fe9f4feddf13568c0510cdaacdd023dbc36a4834847304d5cdafa33df5a6211d5acc1f9690

test:
  secret_key_base: f84073b12dc786fc907026d796132ad392333b5c5d4d6ec1671fbc00758aa701a1fcae7a65dce9a06d57927fb2be80bc9210cf1b38d9aee3c439b223060dc254

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
